shared:
  common_conditions: &common_conditions
    and:
      - 'check-success=test'

queue_rules:
  - name: default
    batch_size: 1
    merge_method: squash
    queue_conditions:
      - <<: *common_conditions
